# Generated by Django 5.0.6 on 2024-05-30 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='afiliado',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='telefono',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='enfermedades',
            field=models.ManyToManyField(to='main.enfermedad'),
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('glucemia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presionSistolica', models.DecimalField(decimal_places=0, max_digits=3)),
                ('presionDiastolica', models.DecimalField(decimal_places=0, max_digits=3)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.historiaclinica')),
            ],
        ),
    ]
